### ISSUE TITLE
Wrong pg timestamp manipulation

### ISSUE THREAD

**Issue by purefun** [dogmatiq/verity#423]
https://github.com/dogmatiq/verity/blob/0e82c7e85bbe5342a4f1d8006beb3bfc8496858e/persistence/sqlpersistence/postgres/lock.go#L32-L43

The `ttl` default value is `10 * time.Second`, which is `10_000_000_000` in nano second. In pg, the timestamp is:

```sql
SELECT EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
-- 1631437551.97961
```

This causes the error `interval field value out of range: "10000000000"` from postgres:12, postgres:13 .

**Comment by jmalloc** [comment]
This issue is not present when using https://github.com/jackc/pgx, so if it's possible use that driver instead that will be the path of least resistance.

I'm assuming you're using https://github.com/lib/pq, which is intended to be supported but is not currently being tested, so I'll rectify that.
