### ISSUE TITLE
Question: How to run multiple verity engine instances for one app?

### ISSUE THREAD

**Issue by purefun** [dogmatiq/verity#424]
I found holding the lock will prevent scaling. If there is a new version of instance, how to deploy it smoothly?

https://github.com/dogmatiq/verity/blob/0e82c7e85bbe5342a4f1d8006beb3bfc8496858e/persistence/sqlpersistence/datastore.go#L183-L215

**Comment by jmalloc** [comment]
Unfortunately, this is just how Verity works right now (it hasn't received its first release yet). This restriction will go away in the future.

The plan is to shard work across instances based on message routes (instance IDs returned from the various routing methods on the handler interfaces). We don't (currently) intend to shard the datastore, instead we'll likely use something like CockroachDB in a cluster (postgres compatible), accessible by all Verity instances. We have a prototype that implements the work sharding, but I don't currently have a timeline for when I will get to address it properly.

**Comment by purefun** [comment]
Thank a lot.
